apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: node-web-app-tt
spec:
  params:
    - name: environment
      description: argocd app
    - name: url
      description: git url
    - name: revision
      description: git revision
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: node-web-app-pipeline-run-
        namespace: node-web-project
      spec:
        pipelineRef:
          name: node-web-app-pipeline
        params:
          - name: deployment_environment
            value: $(params.environment)
          - name: url
            value: $(params.url)
          - name: revision
            value: $(params.revision)
          - name: image
            value: tiggel/node-web-demo:0.1
          - name: path-to-docker-file
            value: /workspace/source/Dockerfile
        workspaces:
          - name: git-source # this workspace name must be declared in the Pipeline
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce # access mode may affect how you can use this volume in parallel tasks
                resources:
                  requests:
                    storage: 1Gi
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: node-web-app-tb
spec:
  params:
    - name: url
      value: https://github.com/Tiggel/node-web-app.git
    - name: revision
      value: master
    - name: environment
      value: dev
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: node-web-app-el
spec:
  #serviceAccountName: pipeline
  triggers:
    - name: trigger-argo
      bindings:
        - ref: node-web-app-tb
      template:
        name: node-web-app-tt
  serviceType: LoadBalancer
