apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: node-web-app-tt
spec:
  params:
    - name: deployment_environment
      type: string
    - name: commit
      type: string
  resourcetemplates:
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        generateName: node-web-app-pipeline-run-
        namespace: node-web-project
      spec:
        pipelineRef:
          name: node-web-app-pipeline
        params:
          - name: deployment_environment
            value: $(params.deployment_environment)
          - name: commit
            value: $params.commit)
        resources:
          - name: node-web-app-git
            resourceRef:
              name: node-web-app-source
          - name: node-web-app-img
            resourceRef:
              name: node-web-app-image
        #serviceAccountName: pipeline
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: node-web-app-tb
spec:
  params:
    - name: git-repo-url
      value: https://github.com/Tiggel/node-web-app.git
    - name: git-revision
      value: master
    - name: git-repo-name
      value: tekton-webinar
    - name: deployment_environment
      value: dev
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: node-web-app-el
spec:
  #serviceAccountName: pipeline
  triggers:
    - name: trigger-argo
      interceptors:
        - cel:
            filter: >-
              (header.match('X-GitHub-Event', 'push')) &&
               body.ref.startsWith('refs/heads/master')
      bindings:
        - ref: node-web-app-tb
      template:
        name: node-web-app-tt
  serviceType: LoadBalancer
