apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: node-web-app-pipeline
  namespace: node-web-project
  labels:
    app: node
    component: tekton
spec:
  params:
    - name: git-url
    - name: git-revision
    - name: image-name
    - name: deployment_environment
    - name: path-to-docker-file
  workspaces:
    - name: git-source
  tasks:
    - name: fetch-from-git
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)
      workspaces:
        - name: output
          workspace: git-source
    - name: build-image
      taskRef:
        name: kaniko
      params:
        - name: IMAGE
          value: $(params.image-name)
        - name: DOCKERFILE
          value: $(params.path-to-docker-file)
      workspaces:
        - name: source
          workspace: git-source
      runAfter:
        - fetch-from-git
    - name: argocd-sync-deployment
      params:
        - name: application-name
          value: $(params.deployment_environment)
        - name: flags
          value: '--insecure'
        - name: argocd-version
          value: v1.5.2
      runAfter:
        - build-image
      taskRef:
        kind: Task
        name: argocd-task-sync-and-wait