apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: node-web-app-pipeline
  namespace: node-web-project
  labels:
    app: node
    component: tekton
spec:
  params:
    - name: deployment_environment
      description: the environment to deploy to with argocd, which is the argocd application to use
      default: dev
    - name: image
      default: tiggel/node-web-demo:latest
  resources:
    - name: node-web-app-git
      type: git
    - name: node-web-app-img
      type: image
  tasks:
    - name: build-and-publish-image
      params:
        - name: DOCKERFILE
          value: ./Dockerfile
      resources:
        inputs:
          - name: source
            resource: node-web-app-git
        outputs:
          resources:
          - name: image
            resourceSpec:
              type: image
              params:
              - name: url
                value: $(params.image)
      taskRef:
        kind: ClusterTask
        name: buildah
    - name: argocd-sync-deployment
      params:
        - name: application-name
          value: $(params.deployment_environment)
        - name: flags
          value: '--insecure'
        - name: argocd-version
          value: v1.5.2
      runAfter:
        - build-and-publish-image
      taskRef:
        kind: Task
        name: argocd-task-sync-and-wait