apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: node-web-app-tt
spec:
  resourcetemplates:
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        generateName: node-web-app-pipeline-run-
        namespace: node-web-project
      spec:
        pipelineRef:
          name: node-web-app-pipeline
        resources:
          - name: node-web-app-git
            resourceRef:
              name: node-web-app-source
          - name: node-web-app-img
            resourceRef:
              name: node-web-app-image
        #serviceAccountName: pipeline
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: node-web-app-tb
spec:
  params:
    - name: git-repo-url
      value: https://github.com/Tiggel/node-web-app.git
    - name: git-revision
      value: master
    - name: git-repo-name
      value: tekton-webinar
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: node-web-app-el
spec:
  #serviceAccountName: pipeline
  triggers:
    - bindings:
        - name: node-web-app-tb
      template:
        name: node-web-app-tt
  serviceType: LoadBalancer
