apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-web-app-deployment
spec:
  selector:
    matchLabels:
      app: node-web-app
  replicas: 3
  template:
    metadata:
      labels:
        app: node-web-app
        version: 1.1.8
    spec:
      containers:
        - name: node-web-app
          image: tiggel/node-web-demo:eea136da669f80d64099499fa7a15d51244f6f37
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: dockercreds
